server:
  port: 80

#spring dataSource Info
#spring JSON Info
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: rootroot
    url: jdbc:mysql:///mmall
    username: root
  jackson:
    default-property-inclusion: non_null

#logger Info
#Mybatis Info
mybatis:
  type-aliases-package: com.houfalyu.mmall.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      houfalyu:
        mmall:
          mapper: debug
